### ISSUE TITLE
头文件包含Range: bytes=0-

### ISSUE THREAD

**Issue by w2599** [SailyTeam/Saily#100]
当头文件包含这个Range: bytes=0-时..
某些源下载deb会返回空文件

出现 验证失败错误1

**Comment by Lakr233** [comment]
请考虑让软件源支持 content-range .........

**Comment by Lakr233** [comment]
我认为这个功能会显著影响用户体验 且在服务端做这个 feature 应该比在客户端擦屁股兜底会方便一些

晚点我看看怎么做比较好

**Comment by w2599** [comment]
大佬不用做选择题..都要就行.出个选项控制.嘿嘿

**Comment by Lakr233** [comment]
Fixed 15dfaa2
