### ISSUE TITLE
增加批量屏蔽的功能

### ISSUE THREAD

**Issue by HuChundong** [SailyTeam/Saily#102]
1. 目前Rootless的特殊性，可能很多更新的基础依赖并不适配，需要一次性屏蔽多个，是否考虑整一个批量屏蔽的功能

**Comment by Lakr233** [comment]
加在哪里呢.... 我不知道耶～ 😂

**Comment by Lakr233** [comment]
还是自己手动点一下吧 毕竟也是个确认的过程 避免后面遇到问题不知道自己做了啥

**Comment by augustobob** [comment]
The blocked  packages list are cleaning after some time, and there’s some packages we want to skip for now, I almost updated them, hope it gets fixed soon

**Comment by jinchunyou** [comment]
> 加在哪里呢.... 我不知道耶～ 😂
能不能增加左滑加入卸载队列和重装，类似于sileo

**Comment by Lakr233** [comment]
Close due to outdated.
