### ISSUE TITLE
Uninstall error

### ISSUE THREAD

**Issue by ramunozp** [SailyTeam/Saily#106]
I installed edge 3 on xina15 and it gives problems, the tweak works but it doesn't let the photos app open.  when can you fix it?  I try to uninstall it and I can't, because it adds components that would break everything, for example, the apt library.

![AF50E012-C15F-4A04-9062-AE68C9B50589](https://user-images.githubusercontent.com/24207310/208789740-b5c33e3f-abf5-42a8-81ab-7e4338581857.jpeg)

**Comment by Lakr233** [comment]
fixed inside rootless 3.0
