### ISSUE TITLE
Repository can’t update 

### ISSUE THREAD

**Issue by dhd111** [SailyTeam/Saily#111]
I can’t update repository i don’t know why 
But this is the  log  

———————————————————————

[App]
* |info| 2023-02-13_21-06-26| 
wiki.qaq.chromatic.release - 1654050540
Build: Wednesday, 1 June 2022 at 5:29:00 AM Arabian Standard Time
Location:
    [*] /Applications/chromatic.app
    [*] /var/mobile/Documents/wiki.qaq.chromatic
Environment: uid 501 gid 501
[BinaryFinder]
* |info| 2023-02-13_21-06-26| setting up binary cp at /bin/cp
* |info| 2023-02-13_21-06-26| setting up binary chmod at /bin/chmod
* |info| 2023-02-13_21-06-26| setting up binary mv at /bin/mv
* |info| 2023-02-13_21-06-26| setting up binary mkdir at /bin/mkdir
* |info| 2023-02-13_21-06-26| setting up binary touch at /bin/touch
* |info| 2023-02-13_21-06-26| setting up binary rm at /bin/rm
* |info| 2023-02-13_21-06-26| setting up binary kill at /bin/kill
* |info| 2023-02-13_21-06-26| setting up binary killall at /usr/bin/killall
* |info| 2023-02-13_21-06-26| setting up binary sbreload at /usr/bin/sbreload
* |info| 2023-02-13_21-06-26| setting up binary uicache at /usr/bin/uicache
* |info| 2023-02-13_21-06-26| setting up binary apt at /usr/bin/apt
* |info| 2023-02-13_21-06-26| setting up binary dpkg at /usr/bin/dpkg
[AuxiliaryExecute]
* |info| 2023-02-13_21-06-26| /usr/sbin/chromaticspawn: ipc.create.root.session /var/mobile/Documents/wiki.qaq.chromatic/wiki.qaq.root.sessions
[AuxiliaryExecuteWrapper]
* |info| 2023-02-13_21-06-26| created privileged session ticket://6B2510A6-B6BE-4611-830D-710F9015F967-AA55
* |info| 2023-02-13_21-06-26| ticket located at /var/mobile/Documents/wiki.qaq.chromatic/wiki.qaq.root.sessions
[AuxiliaryExecute]
* |info| 2023-02-13_21-06-26| /usr/sbin/chromaticspawn: whoami
[Privilege]
* |info| 2023-02-13_21-06-26| stdout: [root]
* |info| 2023-02-13_21-06-26| stderr: []
[Bugsnag]
* |info| 2023-02-13_21-06-26| user id: d3421c3c737a86eebd66b58d8a7519199e4cbf05
[MGCopyAnswer]
* |info| 2023-02-13_21-06-26| UniqueDeviceID returned udid 25 long
[AptRepository.RepositoryCenter]
* |info| 2023-02-13_21-06-26| initializing manager
* |info| 2023-02-13_21-06-26| reporting to work at /var/mobile/Documents/wiki.qaq.chromatic/RepositoryCenter
[<chromatic.SceneDelegate: 0x282678740>]
* |info| 2023-02-13_21-06-26| sceneDidBecomeActive
[AptRepository.PackageCenter]
* |info| 2023-02-13_21-06-26| updating installation info reported 426 pacakges
* |info| 2023-02-13_21-06-26| updating installation info reported 426 pacakges
* |info| 2023-02-13_21-06-27| package tracing database updated in 0.08s
[AptRepository.RepositoryCenter]
* |info| 2023-02-13_21-06-28| persist engine reported 31 repository
[AptRepository.PackageCenter]
* |info| 2023-02-13_21-06-28| compiling packages
[<chromatic.SceneDelegate: 0x282678740>]
* |info| 2023-02-13_21-06-28| sceneDidBecomeActive
[AptRepository.PackageCenter]
* |info| 2023-02-13_21-06-28| updating installation info reported 426 pacakges
* |info| 2023-02-13_21-06-28| package tracing database updated in 0.03s
* |info| 2023-02-13_21-06-28| completed compiling packages in 0.38 seconds
[SGRenet]
* |info| 2023-02-13_21-06-28| resolveNetworkProblemForApp withBundleId wiki.qaq.chromatic.release returns 0
[chromatic.CariolNetwork]
* |info| 2023-02-13_21-06-28| reporting 0 download caches
[AuxiliaryExecute]
* |info| 2023-02-13_21-06-28| /usr/sbin/chromaticspawn: /bin/cp -f /var/mobile/Library/Caches/com.apple.Preferences/AppleAccountIcon@2x.png /var/mobile/Documents/wiki.qaq.chromatic/AppleAccountIcon@2x.png
* |info| 2023-02-13_21-06-28| /usr/sbin/chromaticspawn: /bin/chmod 777 /var/mobile/Documents/wiki.qaq.chromatic/AppleAccountIcon@2x.png
[AppleAvatar]
* |verbose| 2023-02-13_21-06-28| exec: cp: cannot stat '/var/mobile/Library/Caches/com.apple.Preferences/AppleAccountIcon@2x.png': No such file or directory
[AptRepository.PackageCenter]
* |info| 2023-02-13_21-06-28| package tracing database updated in 0.26s
[AptRepository.RepositoryCenter]
* |verbose| 2023-02-13_21-06-31| update https://opa334.github.io enter stage 1
* |verbose| 2023-02-13_21-06-31| update https://repo.ikghd.me enter stage 1
* |verbose| 2023-02-13_21-06-31| update https://yourtweaksaresh.it enter stage 1
* |verbose| 2023-02-13_21-06-31| update https://creaturecoding.com/repo enter stage 1
* |verbose| 2023-02-13_21-06-31| update https://apt.fouadraheb.com enter stage 1
* |verbose| 2023-02-13_21-06-31| update https://cydia.akemi.ai enter stage 1
* |verbose| 2023-02-13_21-06-31| update https://repo.dynastic.co enter stage 1
* |verbose| 2023-02-13_21-06-31| update https://miro92.com/repo enter stage 1
* |verbose| 2023-02-13_21-06-31| update https://cydia.ichitaso.com enter stage 1
* |verbose| 2023-02-13_21-06-31| update https://ios.jjolano.me enter stage 1
* |verbose| 2023-02-13_21-06-31| update https://havoc.app enter stage 1
* |verbose| 2023-02-13_21-06-31| update https://apt.alfhaily.me enter stage 1
* |verbose| 2023-02-13_21-06-31| update https://level3tjg.me/repo enter stage 1
* |verbose| 2023-02-13_21-06-31| update https://julio.hackyouriphone.org enter stage 1
* |verbose| 2023-02-13_21-06-31| update https://jakeajames.github.io enter stage 1
* |verbose| 2023-02-13_21-06-31| update https://julioverne.github.io enter stage 1
* |verbose| 2023-02-13_21-06-31| update https://apt.bingner.com enter stage 1
* |info| 2023-02-13_21-06-35| repository https://arm64e.com/repo was not found
* |info| 2023-02-13_21-06-35| repository https://arm64e.com/repo was not found
* |verbose| 2023-02-13_21-06-36| update https://opa334.github.io enter stage 2
* |verbose| 2023-02-13_21-06-36| update https://creaturecoding.com/repo enter stage 2
* |info| 2023-02-13_21-06-36| https://creaturecoding.com/repo complete compiler invoke in 0.00 second
* |verbose| 2023-02-13_21-06-36| update https://creaturecoding.com/repo enter stage 3
* |verbose| 2023-02-13_21-06-36| update https://cydia.akemi.ai enter stage 2
* |info| 2023-02-13_21-06-36| https://cydia.akemi.ai complete compiler invoke in 0.00 second
* |verbose| 2023-02-13_21-06-36| update https://julioverne.github.io enter stage 2
* |info| 2023-02-13_21-06-36| https://julioverne.github.io complete compiler invoke in 0.00 second
* |verbose| 2023-02-13_21-06-36| update https://julioverne.github.io enter stage 3
* |verbose| 2023-02-13_21-06-36| update https://miro92.com/repo enter stage 2
* |info| 2023-02-13_21-06-36| https://miro92.com/repo complete compiler invoke in 0.00 second
* |verbose| 2023-02-13_21-06-36| update https://miro92.com/repo enter stage 3
* |verbose| 2023-02-13_21-06-36| update https://yourtweaksaresh.it enter stage 2
* |verbose| 2023-02-13_21-06-36| update https://level3tjg.me/repo enter stage 2
* |info| 2023-02-13_21-06-36| https://level3tjg.me/repo complete compiler invoke in 0.00 second
* |verbose| 2023-02-13_21-06-36| update https://level3tjg.me/repo enter stage 3
* |verbose| 2023-02-13_21-06-36| update https://repo.ikghd.me enter stage 2
* |info| 2023-02-13_21-06-36| https://repo.ikghd.me complete compiler invoke in 0.00 second
* |verbose| 2023-02-13_21-06-36| update https://repo.ikghd.me enter stage 3
* |verbose| 2023-02-13_21-06-36| update https://repo.dynastic.co enter stage 2
* |info| 2023-02-13_21-06-36| https://repo.dynastic.co complete compiler invoke in 0.00 second
* |verbose| 2023-02-13_21-06-36| update https://repo.dynastic.co enter stage 3
* |verbose| 2023-02-13_21-06-36| update https://ios.jjolano.me enter stage 2
* |info| 2023-02-13_21-06-36| https://ios.jjolano.me complete compiler invoke in 0.00 second
* |verbose| 2023-02-13_21-06-36| update https://ios.jjolano.me enter stage 3
* |verbose| 2023-02-13_21-06-36| update https://havoc.app enter stage 2
* |info| 2023-02-13_21-06-36| https://havoc.app complete compiler invoke in 0.00 second
* |verbose| 2023-02-13_21-06-36| update https://havoc.app enter stage 3
* |verbose| 2023-02-13_21-06-36| update https://julio.hackyouriphone.org enter stage 2
* |info| 2023-02-13_21-06-36| https://julio.hackyouriphone.org complete compiler invoke in 0.00 second
* |verbose| 2023-02-13_21-06-36| update https://julio.hackyouriphone.org enter stage 3
* |info| 2023-02-13_21-06-36| https://yourtweaksaresh.it complete compiler invoke in 0.00 second
* |info| 2023-02-13_21-06-36| https://opa334.github.io complete compiler invoke in 0.00 second
* |verbose| 2023-02-13_21-06-36| update https://opa334.github.io enter stage 3
* |verbose| 2023-02-13_21-06-36| update https://cydia.akemi.ai enter stage 3
* |verbose| 2023-02-13_21-06-36| update https://apt.bingner.com enter stage 2
* |verbose| 2023-02-13_21-06-36| update https://apt.alfhaily.me enter stage 2
* |info| 2023-02-13_21-06-36| https://apt.alfhaily.me complete compiler invoke in 0.00 second
* |verbose| 2023-02-13_21-06-36| update https://apt.alfhaily.me enter stage 3
* |verbose| 2023-02-13_21-06-36| update https://cydia.ichitaso.com enter stage 2
* |info| 2023-02-13_21-06-36| https://apt.bingner.com complete compiler invoke in 0.00 second
* |verbose| 2023-02-13_21-06-36| update https://apt.bingner.com enter stage 3
* |verbose| 2023-02-13_21-06-36| update https://yourtweaksaresh.it enter stage 3
* |verbose| 2023-02-13_21-06-36| update https://apt.fouadraheb.com enter stage 2
* |verbose| 2023-02-13_21-06-36| update https://jakeajames.github.io enter stage 2
* |info| 2023-02-13_21-06-36| https://jakeajames.github.io complete compiler invoke in 0.00 second
* |verbose| 2023-02-13_21-06-36| update https://jakeajames.github.io enter stage 3
* |info| 2023-02-13_21-06-36| https://cydia.ichitaso.com complete compiler invoke in 0.00 second
* |verbose| 2023-02-13_21-06-36| update https://cydia.ichitaso.com enter stage 3
* |info| 2023-02-13_21-06-36| https://apt.fouadraheb.com complete compiler invoke in 0.00 second
* |verbose| 2023-02-13_21-06-36| update https://apt.fouadraheb.com enter stage 3
* |verbose| 2023-02-13_21-06-41| update https://julioverne.github.io enter stage 4
* |info| 2023-02-13_21-06-41| Complete update on https://julioverne.github.io in 10.00 seconds
===>
    Repository [julioverne] julioverne's Tweaks
    * Release: 0
    * Package: 0
===>
* |info| 2023-02-13_21-06-41| update engine reported 12 pending and 16 in queue
* |verbose| 2023-02-13_21-06-41| update https://creaturecoding.com/repo enter stage 4
[AptRepository.PackageCenter]
* |info| 2023-02-13_21-06-41| compiling packages
[AptRepository.RepositoryCenter]
* |verbose| 2023-02-13_21-06-41| update https://miro92.com/repo enter stage 4
* |info| 2023-02-13_21-06-41| Complete update on https://creaturecoding.com/repo in 10.01 seconds
===>
    Repository [CreatureCoding Repo] CreatureSurvive's marketplace
    * Release: 0
    * Package: 0
===>
* |info| 2023-02-13_21-06-41| update engine reported 12 pending and 15 in queue
* |info| 2023-02-13_21-06-41| Complete update on https://miro92.com/repo in 10.01 seconds
===>
    Repository [MiRO92] MiRO - This is my public repo.
    * Release: 0
    * Package: 0
===>
* |info| 2023-02-13_21-06-41| update engine reported 12 pending and 14 in queue
[AptRepository.PackageCenter]
* |info| 2023-02-13_21-06-41| compiler returned due to token mismatch
* |info| 2023-02-13_21-06-41| compiling packages
* |info| 2023-02-13_21-06-41| compiler returned due to token mismatch
* |info| 2023-02-13_21-06-41| compiling packages
[AptRepository.RepositoryCenter]
* |verbose| 2023-02-13_21-06-41| update https://level3tjg.me/repo enter stage 4
* |info| 2023-02-13_21-06-41| Complete update on https://level3tjg.me/repo in 10.01 seconds
===>
    Repository [level3tjg's repo] 1.0
    * Release: 0
    * Package: 0
===>
* |info| 2023-02-13_21-06-41| update engine reported 12 pending and 13 in queue
* |verbose| 2023-02-13_21-06-41| update https://ios.jjolano.me enter stage 4
* |info| 2023-02-13_21-06-41| Complete update on https://ios.jjolano.me in 10.01 seconds
===>
    Repository [jjolano] personal tweak repository
    * Release: 0
    * Package: 0
===>
* |info| 2023-02-13_21-06-41| update engine reported 12 pending and 12 in queue
* |verbose| 2023-02-13_21-06-41| update https://havoc.app enter stage 4
[AptRepository.PackageCenter]
* |info| 2023-02-13_21-06-41| compiler returned due to token mismatch
* |info| 2023-02-13_21-06-41| compiling packages
[AptRepository.RepositoryCenter]
* |verbose| 2023-02-13_21-06-41| update https://repo.dynastic.co enter stage 4
* |verbose| 2023-02-13_21-06-41| update https://cydia.akemi.ai enter stage 4
* |info| 2023-02-13_21-06-41| Complete update on https://cydia.akemi.ai in 10.02 seconds
===>
    Repository [Karen/あけみ's Repo] Karen/あけみ's Cydia/APT repository.
    * Release: 0
    * Package: 0
===>
* |info| 2023-02-13_21-06-41| update engine reported 12 pending and 11 in queue
* |verbose| 2023-02-13_21-06-41| update https://julio.hackyouriphone.org enter stage 4
* |info| 2023-02-13_21-06-41| Complete update on https://julio.hackyouriphone.org in 10.02 seconds
===>
    Repository [julioverne] development by julioverne.. Special thanks to HackYouriPhone for host this repo. Updated at: 1660084264
    * Release: 0
    * Package: 0
===>
* |verbose| 2023-02-13_21-06-41| update https://opa334.github.io enter stage 4
* |info| 2023-02-13_21-06-41| Complete update on https://havoc.app in 10.01 seconds
===>
    Repository [Havoc] The Havoc Repository
    * Release: 0
    * Package: 0
===>
* |verbose| 2023-02-13_21-06-41| update https://repo.ikghd.me enter stage 4
* |info| 2023-02-13_21-06-41| update engine reported 12 pending and 10 in queue
* |verbose| 2023-02-13_21-06-41| update https://yourtweaksaresh.it enter stage 4
* |info| 2023-02-13_21-06-41| Complete update on https://yourtweaksaresh.it in 10.03 seconds
===>
    Repository [YourTweaksAreShit] Fr33 skid tweaks
    * Release: 0
    * Package: 0
===>
* |info| 2023-02-13_21-06-41| update engine reported 12 pending and 9 in queue
* |verbose| 2023-02-13_21-06-41| update https://jakeajames.github.io enter stage 4
* |info| 2023-02-13_21-06-41| Complete update on https://jakeajames.github.io in 10.03 seconds
===>
    Repository [Jake's Cydia Repo] Jake James's Cydia Repository
    * Release: 0
    * Package: 0
===>
* |info| 2023-02-13_21-06-41| update engine reported 12 pending and 8 in queue
* |verbose| 2023-02-13_21-06-41| update https://cydia.ichitaso.com enter stage 4
* |verbose| 2023-02-13_21-06-41| update https://apt.fouadraheb.com enter stage 4
* |info| 2023-02-13_21-06-41| Complete update on https://opa334.github.io in 10.04 seconds
===>
    Repository [opa334's Repo] opa334's Cydia Repository
    * Release: 0
    * Package: 0
===>
* |info| 2023-02-13_21-06-41| update engine reported 12 pending and 7 in queue
* |info| 2023-02-13_21-06-41| Complete update on https://repo.ikghd.me in 10.04 seconds
===>
    Repository [iKarwan Repo] Official iKGHD Repo's
    * Release: 0
    * Package: 0
===>
* |info| 2023-02-13_21-06-41| update engine reported 12 pending and 6 in queue
* |info| 2023-02-13_21-06-41| Complete update on https://repo.dynastic.co in 10.04 seconds
===>
    Repository [Dynastic Repo] Discover what your device can do.
    * Release: 0
    * Package: 0
===>
* |info| 2023-02-13_21-06-41| update engine reported 12 pending and 5 in queue
* |verbose| 2023-02-13_21-06-41| update https://apt.bingner.com enter stage 4
* |verbose| 2023-02-13_21-06-41| update https://apt.alfhaily.me enter stage 4
* |info| 2023-02-13_21-06-41| update engine reported 12 pending and 4 in queue
* |info| 2023-02-13_21-06-41| Complete update on https://cydia.ichitaso.com in 10.04 seconds
===>
    Repository [ichitaso] ichitaso's repository
    * Release: 0
    * Package: 0
===>
* |info| 2023-02-13_21-06-41| Complete update on https://apt.fouadraheb.com in 10.04 seconds
===>
    Repository [Fouad's Repo] Betas and small tweaks
    * Release: 0
    * Package: 0
===>
* |info| 2023-02-13_21-06-41| Complete update on https://apt.bingner.com in 10.04 seconds
===>
    Repository [Bingner/Elucubratus] Distribution of Unix Software for iPhoneOS
    * Release: 0
    * Package: 0
===>
* |info| 2023-02-13_21-06-41| update engine reported 12 pending and 3 in queue
* |info| 2023-02-13_21-06-41| update engine reported 12 pending and 2 in queue
* |info| 2023-02-13_21-06-41| update engine reported 12 pending and 1 in queue
* |info| 2023-02-13_21-06-41| Complete update on https://apt.alfhaily.me in 10.04 seconds
===>
    Repository [Alfhaily APT] Alfhaily APT
    * Release: 0
    * Package: 0
===>
* |info| 2023-02-13_21-06-41| update engine reported 12 pending and 0 in queue
[AptRepository.PackageCenter]
* |info| 2023-02-13_21-06-42| compiler returned due to token mismatch
* |info| 2023-02-13_21-06-42| compiling packages
* |info| 2023-02-13_21-06-42| compiler returned due to token mismatch
* |info| 2023-02-13_21-06-42| compiling packages
* |info| 2023-02-13_21-06-42| compiler returned due to token mismatch
* |info| 2023-02-13_21-06-42| compiling packages
* |info| 2023-02-13_21-06-42| compiler returned due to token mismatch
* |info| 2023-02-13_21-06-42| compiling packages
* |info| 2023-02-13_21-06-42| compiler returned due to token mismatch
* |info| 2023-02-13_21-06-42| compiling packages
* |info| 2023-02-13_21-06-42| compiler returned due to token mismatch
* |info| 2023-02-13_21-06-42| compiling packages
* |info| 2023-02-13_21-06-42| compiler returned due to token mismatch
* |info| 2023-02-13_21-06-42| compiling packages
* |info| 2023-02-13_21-06-42| compiler returned due to token mismatch
* |info| 2023-02-13_21-06-42| compiling packages
* |info| 2023-02-13_21-06-42| compiler returned due to token mismatch
* |info| 2023-02-13_21-06-42| compiling packages
* |info| 2023-02-13_21-06-42| compiler returned due to token mismatch
* |info| 2023-02-13_21-06-42| compiling packages
* |info| 2023-02-13_21-06-42| compiler returned due to token mismatch
* |info| 2023-02-13_21-06-42| compiling packages
* |info| 2023-02-13_21-06-42| compiler returned due to token mismatch
* |info| 2023-02-13_21-06-42| compiling packages
* |info| 2023-02-13_21-06-42| compiler returned due to token mismatch
* |info| 2023-02-13_21-06-42| compiling packages
* |info| 2023-02-13_21-06-44| completed compiling packages in 1.17 seconds
[<chromatic.SceneDelegate: 0x282678740>]
* |info| 2023-02-13_21-07-46| sceneDidBecomeActive
* |info| 2023-02-13_21-08-09| sceneDidBecomeActive

**Comment by Lakr233** [comment]
Mostly, there is a network issue.

**Comment by dhd111** [comment]
No i have 
iPhone 11 iOS:14.4.1 and iPhone XR 13.7 
I can update repository all of them in same network 
iPhone 8 iOS:13.3 
iPhone XR iOS:13.3.1

**Comment by Lakr233** [comment]
Fixed Inside Rootless Version
