### ISSUE TITLE
Error installing packages

### ISSUE THREAD

**Issue by rodrigofragadf** [SailyTeam/Saily#113]
I get the following error when I try to install packages.  I'm using an iPhone XS with Xina15.

Preparing Operations
 ===>
 unlocking the system
 2023-02-28 00:04:59.260 chromaticspawn[1616:17686] 连接jailbreak完成
 Permission denied: parent outside the privileged prefix [/Applications/]
 Permission denied: ticket file not found
 [*] returning 19712

 ===>
 start installation
 2023-02-28 00:04:59.352 chromaticspawn[1618:17690] 连接jailbreak完成
 Permission denied: parent outside the privileged prefix [/Applications/]
 Permission denied: ticket file not found
 [*] returning 19712

 Operation Completed

**Comment by Lakr233** [comment]
You are install the wrong version. check ipa file.

**Comment by rodrigofragadf** [comment]
> You are install the wrong version. check ipa file.

I installed from the repository https://sailyteam.github.io/repo/ through Sileo, where can I find the correct version?
