### ISSUE TITLE
Saily Crashing on install/startup

### ISSUE THREAD

**Issue by KGeetings** [SailyTeam/Saily#39]
Saily crashing after first install, won’t open at all. Log has a lot of information. 

> iOS 14.3
iPhone 11 Pro Max
Unc0ver v6.2.0

[Link to Log](https://drive.google.com/file/d/1CxGzUai6AOBUE8tL0OBgv-L9_ls8hi40/view?usp=drivesdk)

**Comment by Lakr233** [comment]
It’s because of the permission issue on your iPhone or an incomplete uicache. Reinstall pls. The crash report say all register to have 0 value means my code isn’t executed any way.

**Comment by KGeetings** [comment]
Ok, so clearly I'm still doing something wrong then. I've uninstalled and reinstalled using Sileo, Installer, and Filza. I've ran uicache and resprung using Filza, and PowerSelector. Something to note though, in Installer, it stops at `processing triggers for cydia (1.1.36) ... bash-5.0#` is this where it's supposed to stop? [Image of Filza install](https://imgur.com/a/oNEoBtr)

**Comment by worf1337** [comment]
Yes, it's meant to stop at `bash-5.0#`

**Comment by Lakr233** [comment]
It should be a uicache bug. Checked your image and the permission should be applied correctly. Try `uicache --all` to fix it.

**Comment by KGeetings** [comment]
Hmm, so I tried uicache --all, and tried uichache through PowerSelector, but it's still crashing. Since I've been meaning to do it for a while any way, I switched to Taurine 1.10 from Unc0ver, and now it seems to install fine. Not sure what was wrong with my Unc0ver jailbreak, but glad it was sorted out. Thanks!

**Comment by Lakr233** [comment]
I haven't test it on uncover tho.... Gonna test it when 14.7 jailbreak rolls out.
