### ISSUE TITLE
swiping to the right on the dashboard view results in a blank page (iPadOS)

### ISSUE THREAD

**Issue by rrk567301** [SailyTeam/Saily#40]

**Comment by Lakr233** [comment]
Can you share an video about it?

**Comment by rrk567301** [comment]
https://user-images.githubusercontent.com/83172201/131392315-ae95c84c-6a5d-4144-bf52-35824015a2a2.mov

**Comment by Lakr233** [comment]
Cant be it! I already block this gesture how?????????? Got it.

**Comment by rrk567301** [comment]
i’m using a tweak called ‘Pancake’, that may be the issue

**Comment by rrk567301** [comment]
i have just found out that this happens with all tabs, not just the dashboard

**Comment by Lakr233** [comment]
Can you provide a detail for this tweak called 'Pancake'? I can not reproduce this issue on any of my devices.

**Comment by rrk567301** [comment]
the tweaks gives you the ability to swipe to the right anywhere to go back instead having to swipe from the left edge, let me try to disable it and see if the issue persists

**Comment by rrk567301** [comment]
yep, disabling fixed the issue

it’s Pancake from https://repo.anthopak.dev/

**Comment by Lakr233** [comment]
Dont feel like to fix somgthing not in my duty 😂

You see there is all kinds of crash in my bugsnag dashboard, somebody trying to decrypt my app and crashed on bfdecrypt, somebody tring to use FLEX and it crashed on function doest not exists in my code, and somebody forget to pack the fluent icons for his debug session and crashed there with a fatalError not finding the resources.

Feeling burnout these days, but I will take the note tho :)

**Comment by Lakr233** [comment]
Fixed 5abedb6e6485a658f2fcbf1fc98e18757ebf21d7
