### ISSUE TITLE
This is more of a feedback not issues

### ISSUE THREAD

**Issue by RickyHunter024** [SailyTeam/Saily#47]
So I just tried it, its wonderful! Fast and sleek just some comments on stuff I experienced or something that needs changing: 

1- I like how as soon as you queue something it automatically starts the download process but I don’t think everyone likes it due to internet so if there was like an option for only enable when on wifi that would be great!

2-I said everything is fast earlier yes it is but, the search might need a bit more improvement with the speed 😅.

 3-Maybe use the space in the homepage to show recommended tweaks, important tweaks etc.

4-Having popular repos installed by default For example: BigBoss or Chariz would be useful.

 5-last point, when a tweak is installed and you are searching for it there is no special sign to show like it’s installed or if it exists then it’s definitely unnoticable .

That’s it and thank you for reading

**Comment by Jmiah3** [comment]
I am told Saily cannot be installed in an iPhone 8. Can Team Saily confirm?

**Comment by Lakr233** [comment]
1 I'll do it later maybe an option in Settings
2,3 Fixed
4 Not Accept, Saily, is not bundled with any jailbreak so there is no reason to do so.
5 Improved

5abedb6e6485a658f2fcbf1fc98e18757ebf21d7
