### ISSUE TITLE
Swipe gestures to install/remove/downgrade a package

### ISSUE THREAD

**Issue by Luki120** [SailyTeam/Saily#49]
What the title says, like Sileo or Zebra have, that'd make it more smooth and better imo. In the "Installed" page.

**Comment by Lakr233** [comment]
I'll take notes.

**Comment by Lakr233** [comment]
This is actually conflicting with the current design, I'm using UICollectionView so..... emmmm

I'll try something else if possible.

**Comment by Luki120** [comment]
Oh, I thought it was a UITableView haha, interesting. Mm maybe [this](https://www.donnywals.com/how-to-add-custom-swipe-actions-to-a-uicollectionviewlistcell/) can help

**Comment by Lakr233** [comment]
Quick action available using ContextMenu.

![Simulator Screen Shot - iPad mini (6th generation) - 2021-10-16 at 09 46 07](https://user-images.githubusercontent.com/25259084/137568874-10e57d06-46e1-497d-810d-802130a82f9a.png)

**Comment by Lakr233** [comment]
while i'm testing multi window support with drag and drop, need around a week to make sure working fine, you may need to download release from github action.
