### ISSUE TITLE
Sources folder

### ISSUE THREAD

**Issue by hellisabove** [SailyTeam/Saily#50]
This is not an issue, but I want to know where does Saily keep it's repositories sources stored because in the default /etc/apt.sources.d is the cydia sources file not the Saily

**Comment by Lakr233** [comment]
It does not contribute to apt, we store it in the document folder, which you can find in setting page. Open download or navigate to the one displayed at bottom.

**Comment by Lakr233** [comment]
If you want to decode the source document, import AptRepository inside Foundation.
