### ISSUE TITLE
Can't find installed package in "Search" if the repo is not added or there isn't one

### ISSUE THREAD

**Issue by Luki120** [SailyTeam/Saily#54]
I'm not sure if this is intended or not, if it is I can close it, but if it's not well yeah, pretty much that. I can't find installed packages when the repository is not added or there isn't one. I find this inconvenient when I'm compiling my tweaks and then I need to search for them to remove them or do something else. Anyways being able to search them in "Installed" page is good, so not really an issue, but thought I'd mention it.

**Comment by Lakr233** [comment]
You mean to search for installed package in "Search" tab other then "Installed" tab?

**Comment by Luki120** [comment]
Yeah

**Comment by Lakr233** [comment]
Done 5abedb6e6485a658f2fcbf1fc98e18757ebf21d7
