### ISSUE TITLE
[CRASH] Invoking sharesheet may lead to app termination on some saturation

### ISSUE THREAD

**Issue by Luki120** [SailyTeam/Saily#55]
When tapping the share button in "Repository" tab or the one located at the top right corner when tapping on a repository it tries to appear for a split second but ends up crashing. Interestingly it doesn't happen in my other device where I run checkra1n, but it does on my main running u0. iPhone XR, 14.3. Happens as well with tweak injection disabled. Here's the crash: https://pastebin.com/WSGbaXDS, hope it provides sufficient debug information.

**Comment by Lakr233** [comment]
I believe there is a system issue where I can not fix them inside my code easily. I have this bug reported widely in Bugsnag backend.

I'll take note on this issue.

```
0  CoreImage           CI::GLContext::init()
1  CoreImage           CI::GLContext::GLContext(CI::GLContext::ShareContextInfo, CGColorSpace*, CGColorSpace*, CI::PixelFormat, bool, unsigned long, bool, bool)
2  CoreImage           CI::GLContext::GLContext(CI::GLContext::ShareContextInfo, CGColorSpace*, CGColorSpace*, CI::PixelFormat, bool, unsigned long, bool, bool)
3  CoreImage           +[CIContext(Internal) internalContextWithEAGLContext:options:]
4  CoreImage           -[CIContext initWithOptions:]
```

**Comment by Lakr233** [comment]
I have restore my phone and try to install uncover and checkra1n but none of them reproduce this issue. Would you like to try a restore?

I doubt there is some tweak randomly change the system environment, and left the changes on the disk.

**Comment by Luki120** [comment]
Yeah sure, I'll let you know in a few days

**Comment by Luki120** [comment]
Hey sorry for the waiting, so I've just restored rootFS but now the previously share button just drops a "copied" toast now? 😅

Edit: just noticed it's disabled by default now. Still getting the crash.. rip. Even after a clean restore and no tweaks had been installed yet

**Comment by Lakr233** [comment]
That’s wired. 😭

**Comment by Luki120** [comment]
Yeah lol. The only "big" system wide tweak I used was MyBloXXX, a system wide ad blocker, which installed a profile and stuff. Other than that there's NeonBoard.. a theming engine, but I don't think that's it. Otherwise no clue

**Comment by Luki120** [comment]
Hey thanks, that worked. However, it triggers [this](https://i.ibb.co/tXB07F1/Saily.jpg) popup. Any ideas? The repo does appear in the text view down below to add it manually anyways.

**Comment by Lakr233** [comment]
Have a look at 1836cb6, someone reported this will work.

**Comment by Luki120** [comment]
I heard the same thing, but I just enabled the share sheet again and it's not crashing anymore lol
