### ISSUE TITLE
[GitHub Action] Help Wanted

### ISSUE THREAD

**Issue by powenn** [SailyTeam/Saily#58]

**Comment by Lakr233** [comment]
Not currently, I'm using my own CI. I'll accept any pr related to GitHub action.

https://lab.qaq.wiki/Lakr233/Protein/-/pipelines

**Comment by powenn** [comment]
> Not currently, I'm using my own CI. I'll accept any pr related to GitHub action.
> 
> 
> 
> https://lab.qaq.wiki/Lakr233/Protein/-/pipelines

Got it,and thanks for merged

**Comment by powenn** [comment]
Solved but not perfect enough yet
timestamp didn't support yet ,will seek for solutions

**Comment by Lakr233** [comment]
timestamp done

**Comment by powenn** [comment]
> timestamp done

excellent ,thanks
