### ISSUE TITLE
[Suggestion] "Add (Repository)" button rework

### ISSUE THREAD

**Issue by detfusco** [SailyTeam/Saily#60]
iPad Pro 10.5", iPadOS 13.5, unc0ver
When you touch the "Add (Repository)" button, you have to scroll all the way down to manually add repos. It'd be much appreciated if it was on the top, above toggle and history section.

Also the default "https://" (in manual input section) isn't getting replaced with the repo link you're copy pasting that already has "https://" hence resulting in a situation like this: "https://https://sailyteam.github.io/". 
It's just a QoL thing that Zebra already does and saves you 1-2 seconds while copy pasting repo links.

**Comment by Lakr233** [comment]
Fixed
