### ISSUE TITLE
[Suggestion] (iPad version) Reworking scrolling down the repository section

### ISSUE THREAD

**Issue by detfusco** [SailyTeam/Saily#61]
iPad Pro 10.5", iPadOS 13.5, unc0ver
It'd be nice to have the 4 essential buttons pinned up top while scrolling down repos. I've made a concept gif, demonstrating what I meant by it: [Gif](https://twitter.com/i/status/1438160379423690759)

**Comment by Lakr233** [comment]
No longer planned.
