### ISSUE TITLE
[Readme modified] add Saily icon and those blue strings

### ISSUE THREAD

**Issue by powenn** [SailyTeam/Saily#62]
Preview on iOS and Mac 
Tested in my other repo
How about this 
https://github.com/powenn/Saily-powentest

![image](https://user-images.githubusercontent.com/72635554/133880967-2c77793e-17a7-485d-82da-920beddc5ff4.jpeg)

![image](https://user-images.githubusercontent.com/72635554/133880986-afe89553-0114-4d6f-a75b-c5344dc54ec1.jpeg)

**Comment by Lakr233** [comment]
I would prefer a simpler one, this one is a bit fancy. I‘ll keep the current readme for now. Thanks for your time.

**Comment by powenn** [comment]
> I would prefer a simpler one, this one is a bit fancy. I‘ll keep the current readme for now. Thanks for your time.

Got it, thanks for response,it's really a nice manager ,excited to it
