### ISSUE TITLE
Make the return key on the keyboard act as a confirmation if the repo inputted is only one

### ISSUE THREAD

**Issue by Luki120** [SailyTeam/Saily#64]
What do you think? Heh, I think it's a good idea just to avoid an extra step when only adding one repository, instead of having to leave the keyboard and then press confirm. Oh and since it's a UITextView it's a bit more of code than for a text field, I have it in Objective-C if you want to. It works great.

**Comment by Lakr233** [comment]
Nope, I tried this, and that would make more misbehave on the user interaction.
