### ISSUE TITLE
zh-Hant localization failed(slolved) and suggestions and iPhone XR issue

### ISSUE THREAD

**Issue by powenn** [SailyTeam/Saily#68]
localization didn't work automatically on my devices, should be Chinese traditional but it was Chinese simpified
need to check this and fix first please 
// already solved
suggest to add a new function like both Sileo and Zebra have
user can set language  in manager settings to choose the language they want
default is follow system and others are selectable

The other problem is Saily install through deb file crash while open on my friend's iPhone XR but ipa worked fine
**note: installed deb fully not usable on my friend' XR,even launch it**
please find some tester to test that ,I am not sure about is that only my friend faced this problem
appericate to your awesome work,these are problems I found, hope you can solve it
**add: localization don't have problems but still suggest add  the function mentioned above**

----------------changed-------------------
zh-hant localization failed solved 
cause by incorrect localization strings
now finding testers to test install through deb file on different devices,to figure out what cause crash

**Comment by Lakr233** [comment]
This might be a problem when syncing localization with crowdin for some I don’t know reason(maybe failed to squash or rebase git commits), but should work fine after recommit. 

Deb installation should work fine, if it’s failing, I need your log during installation.

**Comment by Lakr233** [comment]
And I'm not considering doing a override for language defaults, user should set their language inside Setting.app as Apple required developer to guide the user.

**Comment by powenn** [comment]
> This might be a problem when syncing localization with crowdin for some I don’t know reason(maybe failed to squash or rebase git commits), but should work fine after recommit.
> 
> Deb installation should work fine, if it’s failing, I need your log during installation.

Got it,I will ask him for log,using Cr4shed tweak ,right ?
and how do I send back log to you ?

**Comment by powenn** [comment]
> And I'm not considering doing a override for language defaults, user should set their language inside Setting.app as Apple required developer to guide the user.

okay,thanks for response

**Comment by powenn** [comment]
Hello @Co2333 
I got the crash log
check what cause crashed please 
log here 

[1.txt](https://github.com/SailyTeam/Saily/files/7231136/1.txt)

**Comment by Lakr233** [comment]
> Hello @Co2333
> I got the crash log
> check what cause crashed please
> log here
> 
> [1.txt](https://github.com/SailyTeam/Saily/files/7231136/1.txt)

Could you pls provide your BugsnagID? It’s located at the Setting page.

**Comment by powenn** [comment]
> > Hello @Co2333
> > I got the crash log
> > check what cause crashed please
> > log here
> > [1.txt](https://github.com/SailyTeam/Saily/files/7231136/1.txt)
> 
> Could you pls provide your BugsnagID? It’s located at the Setting page.

But It's not my device,maybe you need his ID ?
he even can't launch Saily,how do he provide it

**Comment by Lakr233** [comment]
I found this in your crash report. 

> 0   ???                           	000000000000000000 0 + 0

Normally this won’t happened to a properly loaded binary. This might be a problem to the jailbreak. If your friend would like to do the research a little bit more, restore his phone and try another jailbreak to see if same thing happen.

**Comment by powenn** [comment]
> I found this in your crash report. 
> 
> 
> 
> > 0   ???                           	000000000000000000 0 + 0
> 
> 
> 
> Normally this won’t happened to a properly loaded binary. This might be a problem to the jailbreak. If your friend would like to do the research a little bit more, restore his phone and try another jailbreak to see if same thing happen. 

Actually he have restored RootFs yesterday due to some reasons,but Saily still crashes,thanks for your response,when new jb tools release,maybe he will try that again

**Comment by Lakr233** [comment]
Do you use Taurine or Uncover? There are two option for XR on 14.3.

**Comment by powenn** [comment]
> Do you use Taurine or Uncover? There are two option for XR on 14.3. 

Both we use Taurine now,unc0ver crashes more often on his phone,so he might not change to that

**Comment by Lakr233** [comment]
That’s wired!

**Comment by powenn** [comment]
> That’s wired!

Yeah,he met a weird thing yesterday,so he restored rootFs,after reboot,Taurine showed err already jb,and reboot again then re jb several times stuck at installing Sileo

**Comment by powenn** [comment]
Hello @Co2333 
I added a launch screen to my test version
It's not a necessary part, so reply if you are interested
test release:
https://github.com/powenn/Saily/releases/tag/test-1.6

![](https://raw.githubusercontent.com/powenn/Saily-powentest/main/photos/06.png)
