### ISSUE TITLE
访问页面怎么不加UDID和系统版本标头

### ISSUE THREAD

**Issue by wxhbts** [SailyTeam/Saily#80]
其他越狱商店都有HTTP_X_UNIQUE_ID  HTTP_X_FIRMWARE HTTP_X_MACHINE这些头文件

**Comment by relisiuol** [comment]
Headers are defined [here](https://github.com/SailyTeam/Saily/blob/28d9e01a882ee9640e30835e2b87908b612980a7/Application/Chromatic/Backend/Common/DeviceInfo.swift#L88).

**Comment by Lakr233** [comment]
We do load those into the web page, but if you are excepting something more, you need to do those your self.

https://github.com/SailyTeam/Saily/blob/main-2.0/Application/Chromatic/Interface/Components/PackageController/ExpandedWebView.swift#L84
