### ISSUE TITLE
The BigBoss depiction violates the Sileo license

### ISSUE THREAD

**Issue by absidue** [SailyTeam/Saily#82]
Specifically this part:

> 3. All advertising materials mentioning features or use of this software must display the following acknowledgement:
> This product includes software developed by the Sileo Team.

That acknowledgment is not included in the depiction for Saily in BigBoss.

https://github.com/Sileo/Sileo/blob/stable/LICENSE

**Comment by Lakr233** [comment]
The depiction says:
> See [Github] for more details. Privacy information and software licenses are there, too.

And read me in the page contains:
This product includes software developed by the Sileo Team.

**Comment by Lakr233** [comment]
I have send a message to the maintainer and he should add this to the page soon.
