### ISSUE TITLE
Unsatisfactory/dangerous handling of dist repos

### ISSUE THREAD

**Issue by beer-psi** [SailyTeam/Saily#84]
Blindly redirecting every user to the iOS 14 dist repo (as shown [here](https://github.com/SailyTeam/Saily/blob/main-2.0/Application/Chromatic/Application/Constant.swift#L45-L48)) is totally not the way to handle repos, as packages that are built differently on 13 and 14, so Saily users on iOS 13 may break their jailbreak. Redirecting everyone to the `iphoneos-arm64/1700` dist is ignorant at best, dangerous at worst.

A sensible (though rudimentary) way to handle "strand apt sources" (dist repos) would be:

```swift
"\(repo_url)/dists/\(dist_name)/Release"
```

I'm sure there are better ways to join URLs, but I'm also sure Saily can handle dist repos better, as they are definitely used in jailbreaks (BigBoss, Elucubratus, Procursus, etc.), unlike what you have stated on Twitter:

> @​foxfortmobile @KatriCameron Then tell me what should I do. I know apt generate the full url using dist components but it is not all required for a jailbreak repo. Since we only use single url as the key to repo, there is no need to do the full implementation. You’re welcome to get that done yourself.

**Comment by Lakr233** [comment]
Fine, I’ll do this next release.

**Comment by worf1337** [comment]
you really sound like you don't give a shit

**Comment by Lakr233** [comment]
Fixed in 969535c, if there is still cases I missed, reopen this issue.
