### ISSUE TITLE
[Suggestion]语言问题（Language）

### ISSUE THREAD

**Issue by sfbeak** [SailyTeam/Saily#85]
现在这个是只能跟着系统默认语言的...建议添加手动更改语言功能。
Now this APP can only follow the system default language... So I suggest adding the ability to manually change the language.

**Comment by Lakr233** [comment]
不是很想做这个 我觉得没有理由这么搞 我知道有插件能干这个事情不妨你装个插件？

**Comment by sfbeak** [comment]
> 不是很想做这个 我觉得没有理由这么搞 我知道有插件能干这个事情不妨你装个插件？

嗯..有插件的嘛...我去看看吧..谢谢
