### ISSUE TITLE
Popup links don’t open from depiction web view

### ISSUE THREAD

**Issue by kirb** [SailyTeam/Saily#88]
Links with a `target="…"` should open in a separate “tab”, i.e. Safari view controller. However, these currently do nothing, because no delegate method has been implemented by Saily to handle such navigations. Chariz uses `<base target="_open">`, so all links on a Chariz depiction should open in either Safari view controller or Safari itself. (`_open` is a Cydia-specific value that specifically opens Safari rather than pushing another web view controller, outside of Cydia this is just equivalent to `_blank`.)

**Comment by Lakr233** [comment]
Implemented and merged.
