### ISSUE TITLE
Don’t override dark mode styles if depiction supports dark mode

### ISSUE THREAD

**Issue by kirb** [SailyTeam/Saily#89]
Not super critical, but a few CSS things in Chariz’s depiction get affected by Saily’s dark mode overrides. Mainly, the dividing lines disappear and link colors become white, both affecting UX. My best suggestion is to check for a `color-scheme` meta tag. Including the token `dark` here is a standard way to indicate the site has native dark mode support and hence no injection is needed. This is already used by extensions like Dark Reader.

Chariz’s looks like this:

```html
<meta name="color-scheme" content="light dark">
```

**Comment by Lakr233** [comment]
Implemented and merged.

**Comment by kirb** [comment]
Thanks for dealing with these so quickly :+1:

By the way, I realised that meta tag was actually not being sent in our depictions. Fixed now.
