### ISSUE TITLE
NOT an issue, looking for Saily’s URL scheme

### ISSUE THREAD

**Issue by Luki120** [SailyTeam/Saily#92]
Hi again haha, just wanted to get the URL scheme from Saily so I can add it [here](https://i.ibb.co/J2TBqgT/9027-F9-FD-7-D82-41-FE-8790-92-BF32-A11934.png) for my repository, thanks. Saily deserves to be there ❤️

**Comment by Lakr233** [comment]
should be `apt-repo://<url here>`

**Comment by Luki120** [comment]
Hey thanks, that worked. However, it triggers [this](https://i.ibb.co/tXB07F1/Saily.jpg) popup. Any ideas? The repo does appear in the text view down below to add it manually anyways.

**Comment by Lakr233** [comment]
I need the log.

**Comment by Luki120** [comment]
Sorry [here](https://www.toptal.com/developers/hastebin/cahekirozo.yaml). However I just realized it’s adding the url without the `:`, after https, that’s probably the issue. No idea why, this is my [index.html](https://github.com/Luki120/luki120.github.io/blob/master/index.html), looks correct I guess :/

**Comment by Lakr233** [comment]
This is fixed in the latest commit.
