### ISSUE TITLE
Havoc的付费插件无法安装。

### ISSUE THREAD

**Issue by ghost** [SailyTeam/Saily#93]
需要去缓存把dld的包修改成deb手动安装

**Comment by Lakr233** [comment]
我前天发现了 但准确的说这个应该是软件源开发者写的不太好...... 我下个版本看看怎么处理好一点

**Comment by Lakr233** [comment]
还有几个功能下次一起发版 这次先不更新 release

**Comment by Lakr233** [comment]
https://github.com/SailyTeam/Saily/actions/runs/1879874891
