### ISSUE TITLE
Procursus mirrors do not work

### ISSUE THREAD

**Issue by asdfugil** [SailyTeam/Saily#94]
List: https://github.com/ProcursusTeam/Procursus/raw/main/mirrors.txt

https://ftp.sudhip.com/procursus
https://repo.quiprr.dev/procursus

does not seem to work. 

/etc/apt/sources.list.d/procursus.sources
```
Types: deb
URIs: https://repo.quiprr.dev/procursus
Suites: iphoneos-arm64/1700
Components: main testing
```
... and I tried to import this to Saily with the import function.

**Comment by Lakr233** [comment]
It is not currently supported to add full Components & Suites over UI, but you can edit the plist file at /var/mobile/Document/wiki.qaq.chromatic/RepositoryCenter/<repo uri sha1 string>. I will add this feature if next release if I still get time to do it.

**Comment by Lakr233** [comment]
Close due to outdated
